/**
 * Soft-preference ontology v0 — the seed vocabulary of ~145 slugs across
 * 10 categories.
 *
 * Bootstrapped from Bright training data (Style, InteriorFeatures,
 * ExteriorFeatures, LotDescription, PropertyCondition, SwimmingPoolType,
 * OtherStructures, Cooling, PrimaryHeat) + hand-curated for
 * lifestyle-location + avoidance-specific.
 *
 * Discipline (CLAUDE.md §6.11):
 *   - LLM Pass-3 prompt includes this full ontology as in-context grounding
 *   - LLM CANNOT invent slugs silently; novel labels land in
 *     `soft_pref_pending` and surface in admin "Ontology Inbox" at 3+
 *     occurrences
 *   - Adding a slug requires migration + alias update + test
 *
 * Slugs use kebab-case with a category prefix: `category.term-with-dashes`.
 * The category prefix is redundant with the `category` field but ensures
 * slug uniqueness across categories and makes them self-describing in logs.
 */

import type { SoftPrefSlugRecord } from "./types.js";

// ============================================================================
// 1. Architectural style (~15)
// ============================================================================

const ARCHITECTURAL_STYLE: SoftPrefSlugRecord[] = [
  {
    slug: "architectural-style.colonial",
    category: "architectural_style",
    displayLabel: "colonial",
    aliases: ["colonial style", "classic colonial", "georgian colonial"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
  },
  {
    slug: "architectural-style.traditional",
    category: "architectural_style",
    displayLabel: "traditional",
    aliases: ["traditional style", "classic"],
    polarity: "bidirectional",
    defaultWeight: 0.6,
  },
  {
    slug: "architectural-style.contemporary",
    category: "architectural_style",
    displayLabel: "contemporary",
    aliases: ["modern contemporary", "current"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
    oppositeSlug: "architectural-style.traditional",
  },
  {
    slug: "architectural-style.craftsman",
    category: "architectural_style",
    displayLabel: "craftsman",
    aliases: ["arts and crafts", "bungalow style", "shingle style"],
    polarity: "bidirectional",
    defaultWeight: 0.75,
  },
  {
    slug: "architectural-style.victorian",
    category: "architectural_style",
    displayLabel: "victorian",
    aliases: ["victorian-era", "queen anne"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
  },
  {
    slug: "architectural-style.tudor",
    category: "architectural_style",
    displayLabel: "tudor",
    aliases: ["tudor revival", "english tudor"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
  },
  {
    slug: "architectural-style.ranch",
    category: "architectural_style",
    displayLabel: "ranch",
    aliases: ["ranch style", "rambler", "single-story ranch"],
    polarity: "bidirectional",
    defaultWeight: 0.65,
  },
  {
    slug: "architectural-style.mid-century-modern",
    category: "architectural_style",
    displayLabel: "mid-century modern",
    aliases: ["mid century", "mcm", "1950s modern"],
    polarity: "bidirectional",
    defaultWeight: 0.75,
  },
  {
    slug: "architectural-style.farmhouse",
    category: "architectural_style",
    displayLabel: "farmhouse",
    aliases: ["modern farmhouse", "farmhouse style"],
    polarity: "bidirectional",
    defaultWeight: 0.75,
  },
  {
    slug: "architectural-style.cape-cod",
    category: "architectural_style",
    displayLabel: "cape cod",
    aliases: ["cape", "cape style"],
    polarity: "bidirectional",
    defaultWeight: 0.65,
  },
  {
    slug: "architectural-style.split-level",
    category: "architectural_style",
    displayLabel: "split-level",
    aliases: ["split foyer", "tri-level"],
    polarity: "bidirectional",
    defaultWeight: 0.55,
  },
  {
    slug: "architectural-style.townhouse",
    category: "architectural_style",
    displayLabel: "townhouse",
    aliases: ["row home", "row house", "town home"],
    polarity: "bidirectional",
    defaultWeight: 0.65,
  },
  {
    slug: "architectural-style.modern",
    category: "architectural_style",
    displayLabel: "modern",
    aliases: ["true modern", "architecturally modern"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
  },
  {
    slug: "architectural-style.mediterranean",
    category: "architectural_style",
    displayLabel: "mediterranean",
    aliases: ["spanish", "stucco mediterranean"],
    polarity: "bidirectional",
    defaultWeight: 0.65,
  },
  {
    slug: "architectural-style.industrial-loft",
    category: "architectural_style",
    displayLabel: "industrial loft",
    aliases: ["loft", "industrial style", "warehouse conversion"],
    polarity: "bidirectional",
    defaultWeight: 0.75,
  },
];

// ============================================================================
// 2. Interior style (~15)
// ============================================================================

const INTERIOR_STYLE: SoftPrefSlugRecord[] = [
  {
    slug: "interior-style.warm-traditional",
    category: "interior_style",
    displayLabel: "warm traditional",
    aliases: ["warm classic", "cozy traditional", "lived-in classic"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
  },
  {
    slug: "interior-style.minimal-modern",
    category: "interior_style",
    displayLabel: "minimal modern",
    aliases: ["minimalist", "clean modern", "scandinavian minimal"],
    polarity: "bidirectional",
    defaultWeight: 0.75,
  },
  {
    slug: "interior-style.transitional",
    category: "interior_style",
    displayLabel: "transitional",
    aliases: ["transitional style", "mix of modern and traditional"],
    polarity: "bidirectional",
    defaultWeight: 0.6,
  },
  {
    slug: "interior-style.industrial",
    category: "interior_style",
    displayLabel: "industrial",
    aliases: ["urban industrial", "exposed brick and steel"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
  },
  {
    slug: "interior-style.scandinavian",
    category: "interior_style",
    displayLabel: "scandinavian",
    aliases: ["nordic", "scandi", "hygge"],
    polarity: "bidirectional",
    defaultWeight: 0.75,
  },
  {
    slug: "interior-style.rustic",
    category: "interior_style",
    displayLabel: "rustic",
    aliases: ["rustic charm", "country rustic", "cabin"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
  },
  {
    slug: "interior-style.eclectic",
    category: "interior_style",
    displayLabel: "eclectic",
    aliases: ["mixed style", "curated mix"],
    polarity: "bidirectional",
    defaultWeight: 0.6,
  },
  {
    slug: "interior-style.formal",
    category: "interior_style",
    displayLabel: "formal",
    aliases: ["formal style", "elegant formal"],
    polarity: "bidirectional",
    defaultWeight: 0.55,
  },
  {
    slug: "interior-style.casual",
    category: "interior_style",
    displayLabel: "casual",
    aliases: ["relaxed", "casual style"],
    polarity: "bidirectional",
    defaultWeight: 0.55,
  },
  {
    slug: "interior-style.luxurious",
    category: "interior_style",
    displayLabel: "luxurious",
    aliases: ["luxe", "high-end finishes", "luxury feel"],
    polarity: "bidirectional",
    defaultWeight: 0.75,
  },
  {
    slug: "interior-style.bohemian",
    category: "interior_style",
    displayLabel: "bohemian",
    aliases: ["boho", "boho chic", "eclectic global"],
    polarity: "bidirectional",
    defaultWeight: 0.65,
  },
  {
    slug: "interior-style.cozy",
    category: "interior_style",
    displayLabel: "cozy",
    aliases: ["snug", "warm and cozy", "intimate"],
    polarity: "bidirectional",
    defaultWeight: 0.6,
  },
  {
    slug: "interior-style.polished",
    category: "interior_style",
    displayLabel: "polished",
    aliases: ["polished finish", "high-end polish"],
    polarity: "bidirectional",
    defaultWeight: 0.65,
  },
  {
    slug: "interior-style.lived-in",
    category: "interior_style",
    displayLabel: "lived-in",
    aliases: ["broken in", "comfortable wear"],
    polarity: "bidirectional",
    defaultWeight: 0.5,
  },
  {
    slug: "interior-style.character-rich",
    category: "interior_style",
    displayLabel: "character-rich",
    aliases: ["full of character", "characterful", "original details"],
    polarity: "bidirectional",
    defaultWeight: 0.75,
  },
];

// ============================================================================
// 3. Layout (~12)
// ============================================================================

const LAYOUT: SoftPrefSlugRecord[] = [
  {
    slug: "layout.open-floor-plan",
    category: "layout",
    displayLabel: "open floor plan",
    aliases: ["open concept", "open layout", "great room flow"],
    polarity: "bidirectional",
    defaultWeight: 0.8,
    oppositeSlug: "layout.defined-rooms",
  },
  {
    slug: "layout.defined-rooms",
    category: "layout",
    displayLabel: "defined rooms",
    aliases: ["compartmentalized", "traditional rooms", "separated spaces"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
    oppositeSlug: "layout.open-floor-plan",
  },
  {
    slug: "layout.single-level",
    category: "layout",
    displayLabel: "single level",
    aliases: ["one story", "single story", "no stairs"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
  },
  {
    slug: "layout.multi-level",
    category: "layout",
    displayLabel: "multi-level",
    aliases: ["multiple floors", "two-story", "three-story"],
    polarity: "bidirectional",
    defaultWeight: 0.5,
  },
  {
    slug: "layout.vaulted-ceilings",
    category: "layout",
    displayLabel: "vaulted ceilings",
    aliases: ["cathedral ceilings", "high ceilings", "soaring ceilings"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
  },
  {
    slug: "layout.abundant-natural-light",
    category: "layout",
    displayLabel: "abundant natural light",
    aliases: ["lots of light", "bright", "sun-filled", "lots of windows"],
    polarity: "bidirectional",
    defaultWeight: 0.85,
    oppositeSlug: "layout.dim-cozy",
  },
  {
    slug: "layout.dim-cozy",
    category: "layout",
    displayLabel: "dim and cozy",
    aliases: ["intimate lighting", "dark and cozy", "moody"],
    polarity: "bidirectional",
    defaultWeight: 0.5,
    oppositeSlug: "layout.abundant-natural-light",
  },
  {
    slug: "layout.flowing-spaces",
    category: "layout",
    displayLabel: "flowing spaces",
    aliases: ["flow", "good flow", "spaces flow into each other"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
  },
  {
    slug: "layout.intimate-scale",
    category: "layout",
    displayLabel: "intimate scale",
    aliases: ["smaller rooms", "intimate rooms", "cozy scale"],
    polarity: "bidirectional",
    defaultWeight: 0.6,
  },
  {
    slug: "layout.spacious-rooms",
    category: "layout",
    displayLabel: "spacious rooms",
    aliases: ["large rooms", "big rooms", "generous rooms"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
  },
  {
    slug: "layout.primary-on-main",
    category: "layout",
    displayLabel: "primary bedroom on main floor",
    aliases: ["main floor primary", "first-floor primary", "downstairs primary"],
    polarity: "bidirectional",
    defaultWeight: 0.75,
  },
  {
    slug: "layout.split-bedrooms",
    category: "layout",
    displayLabel: "split bedrooms",
    aliases: ["primary separated", "bedrooms on opposite ends"],
    polarity: "bidirectional",
    defaultWeight: 0.65,
  },
];

// ============================================================================
// 4. Interior features (~25)
// ============================================================================

const INTERIOR_FEATURES: SoftPrefSlugRecord[] = [
  {
    slug: "interior-features.kitchen-island",
    category: "interior_features",
    displayLabel: "kitchen island",
    aliases: ["island in kitchen", "center island", "cooking island"],
    polarity: "bidirectional",
    defaultWeight: 0.8,
  },
  {
    slug: "interior-features.kitchen-eat-in",
    category: "interior_features",
    displayLabel: "eat-in kitchen",
    aliases: ["breakfast nook in kitchen", "kitchen with eating area"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
  },
  {
    slug: "interior-features.walk-in-closets",
    category: "interior_features",
    displayLabel: "walk-in closets",
    aliases: ["walk-in closet", "walk-ins"],
    polarity: "bidirectional",
    defaultWeight: 0.8,
  },
  {
    slug: "interior-features.hardwood-floors",
    category: "interior_features",
    displayLabel: "hardwood floors",
    aliases: ["wood floors", "real hardwood", "oak floors", "maple floors"],
    polarity: "bidirectional",
    defaultWeight: 0.85,
  },
  {
    slug: "interior-features.recessed-lighting",
    category: "interior_features",
    displayLabel: "recessed lighting",
    aliases: ["can lights", "pot lights", "recessed cans"],
    polarity: "bidirectional",
    defaultWeight: 0.6,
  },
  {
    slug: "interior-features.fireplace-wood-burning",
    category: "interior_features",
    displayLabel: "wood-burning fireplace",
    aliases: ["real fireplace", "wood fireplace"],
    polarity: "bidirectional",
    defaultWeight: 0.75,
  },
  {
    slug: "interior-features.fireplace-gas",
    category: "interior_features",
    displayLabel: "gas fireplace",
    aliases: ["gas-log fireplace"],
    polarity: "bidirectional",
    defaultWeight: 0.6,
  },
  {
    slug: "interior-features.granite-counters",
    category: "interior_features",
    displayLabel: "granite countertops",
    aliases: ["granite counters", "granite tops"],
    polarity: "bidirectional",
    defaultWeight: 0.65,
  },
  {
    slug: "interior-features.quartz-counters",
    category: "interior_features",
    displayLabel: "quartz countertops",
    aliases: ["quartz counters", "quartz tops"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
  },
  {
    slug: "interior-features.stainless-appliances",
    category: "interior_features",
    displayLabel: "stainless appliances",
    aliases: ["stainless steel appliances", "stainless"],
    polarity: "bidirectional",
    defaultWeight: 0.6,
  },
  {
    slug: "interior-features.smart-home",
    category: "interior_features",
    displayLabel: "smart home features",
    aliases: ["smart thermostat", "smart lighting", "home automation"],
    polarity: "bidirectional",
    defaultWeight: 0.65,
  },
  {
    slug: "interior-features.tile-floors",
    category: "interior_features",
    displayLabel: "tile floors",
    aliases: ["tile flooring", "ceramic tile"],
    polarity: "bidirectional",
    defaultWeight: 0.5,
  },
  {
    slug: "interior-features.carpet",
    category: "interior_features",
    displayLabel: "carpet",
    aliases: ["wall-to-wall carpet"],
    polarity: "bidirectional",
    defaultWeight: 0.4,
  },
  {
    slug: "interior-features.breakfast-area",
    category: "interior_features",
    displayLabel: "breakfast area",
    aliases: ["breakfast nook", "morning room"],
    polarity: "bidirectional",
    defaultWeight: 0.6,
  },
  {
    slug: "interior-features.formal-dining-room",
    category: "interior_features",
    displayLabel: "formal dining room",
    aliases: ["separate dining room", "dedicated dining"],
    polarity: "bidirectional",
    defaultWeight: 0.65,
  },
  {
    slug: "interior-features.butlers-pantry",
    category: "interior_features",
    displayLabel: "butler's pantry",
    aliases: ["walk-through pantry", "prep pantry"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
  },
  {
    slug: "interior-features.mudroom",
    category: "interior_features",
    displayLabel: "mudroom",
    aliases: ["mud room", "drop zone"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
  },
  {
    slug: "interior-features.laundry-main-floor",
    category: "interior_features",
    displayLabel: "main floor laundry",
    aliases: ["first floor laundry", "downstairs laundry"],
    polarity: "bidirectional",
    defaultWeight: 0.65,
  },
  {
    slug: "interior-features.laundry-upstairs",
    category: "interior_features",
    displayLabel: "second-floor laundry",
    aliases: ["upstairs laundry", "bedroom-level laundry"],
    polarity: "bidirectional",
    defaultWeight: 0.65,
  },
  {
    slug: "interior-features.basement-finished",
    category: "interior_features",
    displayLabel: "finished basement",
    aliases: ["finished lower level", "basement living space"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
  },
  {
    slug: "interior-features.basement-unfinished",
    category: "interior_features",
    displayLabel: "unfinished basement",
    aliases: ["unfinished lower level", "basement for storage"],
    polarity: "bidirectional",
    defaultWeight: 0.45,
  },
  {
    slug: "interior-features.attic-space",
    category: "interior_features",
    displayLabel: "attic space",
    aliases: ["walk-up attic", "attic storage"],
    polarity: "bidirectional",
    defaultWeight: 0.5,
  },
  {
    slug: "interior-features.crown-molding",
    category: "interior_features",
    displayLabel: "crown molding",
    aliases: ["crown moulding", "decorative moldings"],
    polarity: "bidirectional",
    defaultWeight: 0.55,
  },
  {
    slug: "interior-features.exposed-beams",
    category: "interior_features",
    displayLabel: "exposed beams",
    aliases: ["wood beams", "ceiling beams"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
  },
  {
    slug: "interior-features.upgraded-bathrooms",
    category: "interior_features",
    displayLabel: "upgraded bathrooms",
    aliases: ["renovated bathrooms", "modern bathrooms", "updated baths"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
  },
];

// ============================================================================
// 5. Exterior features (~20)
// ============================================================================

const EXTERIOR_FEATURES: SoftPrefSlugRecord[] = [
  {
    slug: "exterior-features.yard-large",
    category: "exterior_features",
    displayLabel: "large yard",
    aliases: ["big yard", "spacious yard", "plenty of yard"],
    polarity: "bidirectional",
    defaultWeight: 0.8,
    oppositeSlug: "exterior-features.yard-small",
  },
  {
    slug: "exterior-features.yard-medium",
    category: "exterior_features",
    displayLabel: "medium yard",
    aliases: ["moderate yard", "manageable yard"],
    polarity: "bidirectional",
    defaultWeight: 0.6,
  },
  {
    slug: "exterior-features.yard-small",
    category: "exterior_features",
    displayLabel: "small yard",
    aliases: ["minimal yard", "low-maintenance yard"],
    polarity: "bidirectional",
    defaultWeight: 0.5,
    oppositeSlug: "exterior-features.yard-large",
  },
  {
    slug: "exterior-features.pool-in-ground",
    category: "exterior_features",
    displayLabel: "in-ground pool",
    aliases: ["pool", "swimming pool", "inground pool"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
  },
  {
    slug: "exterior-features.deck",
    category: "exterior_features",
    displayLabel: "deck",
    aliases: ["back deck", "wood deck"],
    polarity: "bidirectional",
    defaultWeight: 0.65,
  },
  {
    slug: "exterior-features.patio",
    category: "exterior_features",
    displayLabel: "patio",
    aliases: ["back patio", "stone patio", "concrete patio"],
    polarity: "bidirectional",
    defaultWeight: 0.65,
  },
  {
    slug: "exterior-features.porch-front",
    category: "exterior_features",
    displayLabel: "front porch",
    aliases: ["covered front porch", "wraparound porch"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
  },
  {
    slug: "exterior-features.porch-back",
    category: "exterior_features",
    displayLabel: "back porch",
    aliases: ["screened back porch", "covered back porch"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
  },
  {
    slug: "exterior-features.fenced-yard",
    category: "exterior_features",
    displayLabel: "fenced yard",
    aliases: ["fenced backyard", "privacy fence"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
  },
  {
    slug: "exterior-features.garage-attached",
    category: "exterior_features",
    displayLabel: "attached garage",
    aliases: ["attached two-car", "garage attached to home"],
    polarity: "bidirectional",
    defaultWeight: 0.75,
  },
  {
    slug: "exterior-features.garage-detached",
    category: "exterior_features",
    displayLabel: "detached garage",
    aliases: ["separate garage", "detached two-car"],
    polarity: "bidirectional",
    defaultWeight: 0.55,
  },
  {
    slug: "exterior-features.garage-multi-car",
    category: "exterior_features",
    displayLabel: "multi-car garage",
    aliases: ["three-car garage", "four-car garage", "oversized garage"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
  },
  {
    slug: "exterior-features.driveway-private",
    category: "exterior_features",
    displayLabel: "private driveway",
    aliases: ["dedicated driveway", "off-street parking"],
    polarity: "bidirectional",
    defaultWeight: 0.65,
  },
  {
    slug: "exterior-features.parking-street",
    category: "exterior_features",
    displayLabel: "street parking",
    aliases: ["on-street parking"],
    polarity: "bidirectional",
    defaultWeight: 0.3,
  },
  {
    slug: "exterior-features.mature-trees",
    category: "exterior_features",
    displayLabel: "mature trees",
    aliases: ["old growth trees", "established trees", "tree-lined"],
    polarity: "bidirectional",
    defaultWeight: 0.75,
  },
  {
    slug: "exterior-features.landscaped",
    category: "exterior_features",
    displayLabel: "landscaped",
    aliases: ["professional landscaping", "manicured grounds"],
    polarity: "bidirectional",
    defaultWeight: 0.65,
  },
  {
    slug: "exterior-features.low-maintenance-yard",
    category: "exterior_features",
    displayLabel: "low-maintenance yard",
    aliases: ["xeriscape", "low-care yard"],
    polarity: "bidirectional",
    defaultWeight: 0.65,
  },
  {
    slug: "exterior-features.waterfront",
    category: "exterior_features",
    displayLabel: "waterfront",
    aliases: ["on the water", "water frontage", "lakefront", "riverfront"],
    polarity: "bidirectional",
    defaultWeight: 0.9,
  },
  {
    slug: "exterior-features.view-scenic",
    category: "exterior_features",
    displayLabel: "scenic view",
    aliases: ["beautiful view", "mountain view", "city view"],
    polarity: "bidirectional",
    defaultWeight: 0.8,
  },
  {
    slug: "exterior-features.privacy",
    category: "exterior_features",
    displayLabel: "private setting",
    aliases: ["private lot", "secluded", "tucked away"],
    polarity: "bidirectional",
    defaultWeight: 0.75,
  },
];

// ============================================================================
// 6. Condition (~8)
// ============================================================================

const CONDITION: SoftPrefSlugRecord[] = [
  {
    slug: "condition.new-construction",
    category: "condition",
    displayLabel: "new construction",
    aliases: ["brand new", "newly built", "just-built"],
    polarity: "bidirectional",
    defaultWeight: 0.8,
  },
  {
    slug: "condition.recently-renovated",
    category: "condition",
    displayLabel: "recently renovated",
    aliases: ["fully renovated", "completely updated", "modernized"],
    polarity: "bidirectional",
    defaultWeight: 0.8,
  },
  {
    slug: "condition.well-maintained",
    category: "condition",
    displayLabel: "well-maintained",
    aliases: ["lovingly maintained", "cared for", "move-in ready"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
  },
  {
    slug: "condition.dated-but-functional",
    category: "condition",
    displayLabel: "dated but functional",
    aliases: ["older finishes", "needs cosmetic refresh"],
    polarity: "bidirectional",
    defaultWeight: 0.4,
  },
  {
    slug: "condition.needs-cosmetic-updates",
    category: "condition",
    displayLabel: "needs cosmetic updates",
    aliases: ["paint and floors", "surface-level work"],
    polarity: "bidirectional",
    defaultWeight: 0.4,
  },
  {
    slug: "condition.fixer-upper",
    category: "condition",
    displayLabel: "fixer-upper",
    aliases: ["needs work", "renovation project", "TLC"],
    polarity: "bidirectional",
    defaultWeight: 0.5,
  },
  {
    slug: "condition.original-charm",
    category: "condition",
    displayLabel: "original charm",
    aliases: ["period details preserved", "original features", "unspoiled"],
    polarity: "bidirectional",
    defaultWeight: 0.75,
  },
  {
    slug: "condition.historic",
    category: "condition",
    displayLabel: "historic",
    aliases: ["historic property", "listed historic"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
  },
];

// ============================================================================
// 7. Lifestyle / location (~18)
// ============================================================================

const LIFESTYLE_LOCATION: SoftPrefSlugRecord[] = [
  {
    slug: "lifestyle-location.walkable-neighborhood",
    category: "lifestyle_location",
    displayLabel: "walkable neighborhood",
    aliases: ["walkable", "walking distance", "walk score"],
    polarity: "bidirectional",
    defaultWeight: 0.85,
  },
  {
    slug: "lifestyle-location.suburban-quiet",
    category: "lifestyle_location",
    displayLabel: "quiet suburban",
    aliases: ["quiet suburb", "peaceful suburb", "established suburb"],
    polarity: "bidirectional",
    defaultWeight: 0.75,
  },
  {
    slug: "lifestyle-location.urban-vibrant",
    category: "lifestyle_location",
    displayLabel: "urban vibrant",
    aliases: ["urban", "city living", "vibrant neighborhood"],
    polarity: "bidirectional",
    defaultWeight: 0.8,
  },
  {
    slug: "lifestyle-location.rural-secluded",
    category: "lifestyle_location",
    displayLabel: "rural secluded",
    aliases: ["rural", "country setting", "out in the country"],
    polarity: "bidirectional",
    defaultWeight: 0.75,
  },
  {
    slug: "lifestyle-location.near-good-schools",
    category: "lifestyle_location",
    displayLabel: "near good schools",
    aliases: ["good school district", "top schools", "highly rated schools"],
    polarity: "bidirectional",
    defaultWeight: 0.9,
  },
  {
    slug: "lifestyle-location.near-public-transit",
    category: "lifestyle_location",
    displayLabel: "near public transit",
    aliases: ["close to transit", "near train", "near bus"],
    polarity: "bidirectional",
    defaultWeight: 0.75,
  },
  {
    slug: "lifestyle-location.near-shopping",
    category: "lifestyle_location",
    displayLabel: "near shopping",
    aliases: ["close to shopping", "near retail"],
    polarity: "bidirectional",
    defaultWeight: 0.65,
  },
  {
    slug: "lifestyle-location.near-parks",
    category: "lifestyle_location",
    displayLabel: "near parks",
    aliases: ["close to parks", "near green space", "next to a park"],
    polarity: "bidirectional",
    defaultWeight: 0.75,
  },
  {
    slug: "lifestyle-location.near-water",
    category: "lifestyle_location",
    displayLabel: "near water",
    aliases: ["lake access", "river access", "near beach"],
    polarity: "bidirectional",
    defaultWeight: 0.75,
  },
  {
    slug: "lifestyle-location.low-traffic-street",
    category: "lifestyle_location",
    displayLabel: "low-traffic street",
    aliases: ["quiet street", "low traffic", "cul de sac"],
    polarity: "bidirectional",
    defaultWeight: 0.8,
  },
  {
    slug: "lifestyle-location.commuter-friendly",
    category: "lifestyle_location",
    displayLabel: "commuter friendly",
    aliases: ["easy commute", "good commute", "near highways"],
    polarity: "bidirectional",
    defaultWeight: 0.8,
  },
  {
    slug: "lifestyle-location.family-oriented",
    category: "lifestyle_location",
    displayLabel: "family-oriented neighborhood",
    aliases: ["kid-friendly", "family neighborhood"],
    polarity: "bidirectional",
    defaultWeight: 0.85,
  },
  {
    slug: "lifestyle-location.vibrant-nightlife",
    category: "lifestyle_location",
    displayLabel: "vibrant nightlife",
    aliases: ["nightlife", "bars and restaurants", "lively area"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
  },
  {
    slug: "lifestyle-location.historic-neighborhood",
    category: "lifestyle_location",
    displayLabel: "historic neighborhood",
    aliases: ["historic district", "old town"],
    polarity: "bidirectional",
    defaultWeight: 0.75,
  },
  {
    slug: "lifestyle-location.new-development",
    category: "lifestyle_location",
    displayLabel: "new development",
    aliases: ["new neighborhood", "new community"],
    polarity: "bidirectional",
    defaultWeight: 0.6,
  },
  {
    slug: "lifestyle-location.established-neighborhood",
    category: "lifestyle_location",
    displayLabel: "established neighborhood",
    aliases: ["mature neighborhood", "settled neighborhood"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
  },
  {
    slug: "lifestyle-location.cul-de-sac",
    category: "lifestyle_location",
    displayLabel: "cul-de-sac",
    aliases: ["dead end", "no through traffic"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
  },
  {
    slug: "lifestyle-location.gated-community",
    category: "lifestyle_location",
    displayLabel: "gated community",
    aliases: ["gated neighborhood", "gated"],
    polarity: "bidirectional",
    defaultWeight: 0.6,
  },
];

// ============================================================================
// 8. Amenities (~12)
// ============================================================================

const AMENITIES: SoftPrefSlugRecord[] = [
  {
    slug: "amenities.home-office-dedicated",
    category: "amenities",
    displayLabel: "dedicated home office",
    aliases: ["home office", "office room", "study", "den as office"],
    polarity: "pull_only",
    defaultWeight: 0.9,
  },
  {
    slug: "amenities.in-law-suite",
    category: "amenities",
    displayLabel: "in-law suite",
    aliases: ["mother-in-law suite", "guest suite", "secondary suite"],
    polarity: "pull_only",
    defaultWeight: 0.75,
  },
  {
    slug: "amenities.guest-house",
    category: "amenities",
    displayLabel: "guest house",
    aliases: ["guesthouse", "carriage house", "casita"],
    polarity: "pull_only",
    defaultWeight: 0.75,
  },
  {
    slug: "amenities.workshop",
    category: "amenities",
    displayLabel: "workshop",
    aliases: ["work shop", "maker space", "studio space"],
    polarity: "pull_only",
    defaultWeight: 0.7,
  },
  {
    slug: "amenities.theater-room",
    category: "amenities",
    displayLabel: "theater room",
    aliases: ["media room", "home theater"],
    polarity: "pull_only",
    defaultWeight: 0.65,
  },
  {
    slug: "amenities.wine-cellar",
    category: "amenities",
    displayLabel: "wine cellar",
    aliases: ["wine storage", "wine room"],
    polarity: "pull_only",
    defaultWeight: 0.6,
  },
  {
    slug: "amenities.exercise-room",
    category: "amenities",
    displayLabel: "exercise room",
    aliases: ["home gym", "workout room"],
    polarity: "pull_only",
    defaultWeight: 0.7,
  },
  {
    slug: "amenities.hot-tub",
    category: "amenities",
    displayLabel: "hot tub",
    aliases: ["jacuzzi", "spa"],
    polarity: "pull_only",
    defaultWeight: 0.55,
  },
  {
    slug: "amenities.sauna",
    category: "amenities",
    displayLabel: "sauna",
    aliases: ["dry sauna", "steam room"],
    polarity: "pull_only",
    defaultWeight: 0.5,
  },
  {
    slug: "amenities.outdoor-kitchen",
    category: "amenities",
    displayLabel: "outdoor kitchen",
    aliases: ["built-in grill", "outdoor cooking"],
    polarity: "pull_only",
    defaultWeight: 0.7,
  },
  {
    slug: "amenities.solar-panels",
    category: "amenities",
    displayLabel: "solar panels",
    aliases: ["solar power", "solar array", "PV system"],
    polarity: "pull_only",
    defaultWeight: 0.7,
  },
  {
    slug: "amenities.ev-charger",
    category: "amenities",
    displayLabel: "EV charger",
    aliases: ["electric car charger", "tesla charger"],
    polarity: "pull_only",
    defaultWeight: 0.65,
  },
];

// ============================================================================
// 9. Practical (~10)
// ============================================================================

const PRACTICAL: SoftPrefSlugRecord[] = [
  {
    slug: "practical.low-hoa",
    category: "practical",
    displayLabel: "low HOA",
    aliases: ["modest HOA", "reasonable HOA"],
    polarity: "bidirectional",
    defaultWeight: 0.6,
  },
  {
    slug: "practical.no-hoa",
    category: "practical",
    displayLabel: "no HOA",
    aliases: ["no homeowners association", "non-HOA"],
    polarity: "bidirectional",
    defaultWeight: 0.7,
  },
  {
    slug: "practical.hoa-with-amenities",
    category: "practical",
    displayLabel: "HOA with amenities",
    aliases: ["HOA pool", "HOA clubhouse"],
    polarity: "bidirectional",
    defaultWeight: 0.55,
  },
  {
    slug: "practical.central-ac",
    category: "practical",
    displayLabel: "central air conditioning",
    aliases: ["central air", "central AC"],
    polarity: "pull_only",
    defaultWeight: 0.8,
  },
  {
    slug: "practical.central-heat",
    category: "practical",
    displayLabel: "central heat",
    aliases: ["central heating", "forced air heat"],
    polarity: "pull_only",
    defaultWeight: 0.75,
  },
  {
    slug: "practical.energy-efficient",
    category: "practical",
    displayLabel: "energy efficient",
    aliases: ["high efficiency", "energy star", "low utility bills"],
    polarity: "pull_only",
    defaultWeight: 0.75,
  },
  {
    slug: "practical.smart-home-equipped",
    category: "practical",
    displayLabel: "smart home equipped",
    aliases: ["pre-wired smart home", "smart home ready"],
    polarity: "pull_only",
    defaultWeight: 0.6,
  },
  {
    slug: "practical.hardwired-ethernet",
    category: "practical",
    displayLabel: "hardwired ethernet",
    aliases: ["cat6 wiring", "structured wiring"],
    polarity: "pull_only",
    defaultWeight: 0.55,
  },
  {
    slug: "practical.security-system",
    category: "practical",
    displayLabel: "security system",
    aliases: ["alarm system", "monitored security"],
    polarity: "pull_only",
    defaultWeight: 0.6,
  },
  {
    slug: "practical.well-insulated",
    category: "practical",
    displayLabel: "well-insulated",
    aliases: ["good insulation", "double-pane windows"],
    polarity: "pull_only",
    defaultWeight: 0.7,
  },
];

// ============================================================================
// 10. Avoidance-specific (~10)
// ============================================================================

const AVOIDANCE_SPECIFIC: SoftPrefSlugRecord[] = [
  {
    slug: "avoidance-specific.no-stairs",
    category: "avoidance_specific",
    displayLabel: "no stairs",
    aliases: ["avoid stairs", "stairs are a dealbreaker"],
    polarity: "push_only",
    defaultWeight: 0.9,
  },
  {
    slug: "avoidance-specific.no-shared-walls",
    category: "avoidance_specific",
    displayLabel: "no shared walls",
    aliases: ["no townhouse", "no condo", "detached only"],
    polarity: "push_only",
    defaultWeight: 0.85,
  },
  {
    slug: "avoidance-specific.no-busy-road",
    category: "avoidance_specific",
    displayLabel: "no busy road",
    aliases: ["avoid busy street", "no high-traffic", "off main road"],
    polarity: "push_only",
    defaultWeight: 0.85,
  },
  {
    slug: "avoidance-specific.no-flood-zone",
    category: "avoidance_specific",
    displayLabel: "not in flood zone",
    aliases: ["no flooding history", "avoid flood plain"],
    polarity: "push_only",
    defaultWeight: 0.9,
  },
  {
    slug: "avoidance-specific.no-airport-proximity",
    category: "avoidance_specific",
    displayLabel: "no airport proximity",
    aliases: ["away from airport", "no flight path"],
    polarity: "push_only",
    defaultWeight: 0.8,
  },
  {
    slug: "avoidance-specific.no-deferred-maintenance",
    category: "avoidance_specific",
    displayLabel: "no deferred maintenance",
    aliases: ["no big repairs", "no major work", "no roof issues"],
    polarity: "push_only",
    defaultWeight: 0.85,
  },
  {
    slug: "avoidance-specific.no-pool",
    category: "avoidance_specific",
    displayLabel: "no pool",
    aliases: ["pool is a dealbreaker", "avoid pool"],
    polarity: "push_only",
    defaultWeight: 0.6,
  },
  {
    slug: "avoidance-specific.no-railroad-proximity",
    category: "avoidance_specific",
    displayLabel: "no railroad proximity",
    aliases: ["away from train tracks", "no rail line"],
    polarity: "push_only",
    defaultWeight: 0.8,
  },
  {
    slug: "avoidance-specific.no-high-voltage-lines",
    category: "avoidance_specific",
    displayLabel: "no high-voltage lines",
    aliases: ["away from power lines", "no transmission lines"],
    polarity: "push_only",
    defaultWeight: 0.75,
  },
  {
    slug: "avoidance-specific.no-noisy-neighbors",
    category: "avoidance_specific",
    displayLabel: "no noisy neighbors",
    aliases: ["quiet block", "peaceful surroundings"],
    polarity: "push_only",
    defaultWeight: 0.7,
  },
];

// ============================================================================
// All slugs combined
// ============================================================================

export const SOFT_PREF_SLUGS_V0: SoftPrefSlugRecord[] = [
  ...ARCHITECTURAL_STYLE,
  ...INTERIOR_STYLE,
  ...LAYOUT,
  ...INTERIOR_FEATURES,
  ...EXTERIOR_FEATURES,
  ...CONDITION,
  ...LIFESTYLE_LOCATION,
  ...AMENITIES,
  ...PRACTICAL,
  ...AVOIDANCE_SPECIFIC,
];

export const SOFT_PREF_SLUGS_BY_CATEGORY = {
  architectural_style: ARCHITECTURAL_STYLE,
  interior_style: INTERIOR_STYLE,
  layout: LAYOUT,
  interior_features: INTERIOR_FEATURES,
  exterior_features: EXTERIOR_FEATURES,
  condition: CONDITION,
  lifestyle_location: LIFESTYLE_LOCATION,
  amenities: AMENITIES,
  practical: PRACTICAL,
  avoidance_specific: AVOIDANCE_SPECIFIC,
} as const;
